### ISSUE TITLE
polisy cryptography library issue

### ISSUE THREAD

**Issue by avandeputte** [timekillerj/udi-poly-lutroncaseta#5]
Just got my polisy today.  I tried installing the module,  it install fine.  Trying to run it,  the log shows this error:

```
2019-10-28 16:50:10,734 [MainThread] [INFO ] Received Config from STDIN.
2019-10-28 16:50:10,736 [MainThread] [INFO ] UDI Polyglot v2 Interface 2.0.31 Starting...
2019-10-28 16:50:11,564 [MainThread] [ERROR] Traceback (most recent call last):
2019-10-28 16:50:11,564 [MainThread] [ERROR] File "./lutroncaseta-poly.py", line 10, in <module>
2019-10-28 16:50:11,565 [MainThread] [ERROR] from lutron_caseta_nodes.LutronCasetaController import LutronCasetaController
2019-10-28 16:50:11,566 [MainThread] [ERROR] File "/var/polyglot/nodeservers/LutronCaseta/lutron_caseta_nodes/LutronCasetaController.py", line 9, in <module>
2019-10-28 16:50:11,567 [MainThread] [ERROR] from cryptography import x509
2019-10-28 16:50:11,568 [MainThread] [ERROR] ModuleNotFoundError
2019-10-28 16:50:11,568 [MainThread] [ERROR] :
2019-10-28 16:50:11,568 [MainThread] [ERROR] No module named 'cryptography'
```

So,  I ssh-ed into the polisy to see what's going on.  Running install.sh fails on installing requirements.  Specifically,  the cryptography package does not install,  there is apparently no compiler on polisy

```
[admin@polisy /var/polyglot/nodeservers/LutronCaseta]$ ./install.sh
Collecting polyinterface>=2.0.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a8/33/56195e3c280a21f78de3                                                                                                                                                         9f81c9aa4bf63215eeb550a7dc552ee91001d002/polyinterface-2.0.31.tar.gz
Collecting markdown2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/89/d2/6aef45472f7956646fdc                                                                                                                                                         4cc5284e6f9d00476497a8d167c30b0f78bb75a5/markdown2-2.3.8-py2.py3-none-any.whl
Collecting cryptography>=2.3 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d                                                                                                                                                         5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz (504kB)
     |████████████████████████████████| 512kB 1.4MB/s
  Installing build dependencies ... error
  ERROR: Complete output from command /usr/local/bin/python3.7 /usr/local/lib/py                                                                                                                                                         thon3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip                                                                                                                                                         -build-env-y89sy82c/overlay --no-warn-script-location --no-binary :none: --only-                                                                                                                                                         binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.                                                                                                                                                         8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'':
  ERROR: Collecting setuptools>=40.6.0
    Downloading https://files.pythonhosted.org/packages/db/3c/1065553af43e5f388c                                                                                                                                                         b5ae96f44867470063a2d04c02551104dcb12794bd/setuptools-41.5.1-py2.py3-none-any.wh                                                                                                                                                         l (581kB)
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45                                                                                                                                                         610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting cffi!=1.11.3,>=1.8
    Downloading https://files.pythonhosted.org/packages/0d/aa/c5ac2f337d9a10ee95                                                                                                                                                         d160d47beb8d9400e1b2a46bb94990a0409fe6d133/cffi-1.13.1.tar.gz (460kB)
  Collecting pycparser (from cffi!=1.11.3,>=1.8)
    Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead                                                                                                                                                         1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
  Installing collected packages: setuptools, wheel, pycparser, cffi
    Running setup.py install for pycparser: started
      Running setup.py install for pycparser: finished with status 'done'
    Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Complete output from command /usr/local/bin/python3.7 -u -c 'import                                                                                                                                                          setuptools, tokenize;__file__='"'"'/tmp/pip-install-g0e1xhci/cffi/setup.py'"'"'                                                                                                                                                         ;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'                                                                                                                                                         \r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))                                                                                                                                                         ' install --record /tmp/pip-record-8tldunwo/install-record.txt --single-version-                                                                                                                                                         externally-managed --prefix /tmp/pip-build-env-y89sy82c/overlay --compile:
      ERROR: unable to execute 'cc': No such file or directory
      unable to execute 'cc': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7
      creating build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/error.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      copying cffi/verifier.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/c                                                                                                                                                         ffi
      copying cffi/vengine_cpy.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      copying cffi/__init__.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/c                                                                                                                                                         ffi
      copying cffi/lock.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/recompiler.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7                                                                                                                                                         /cffi
      copying cffi/model.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/cparser.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cf                                                                                                                                                         fi
      copying cffi/cffi_opcode.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      copying cffi/api.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      copying cffi/setuptools_ext.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64                                                                                                                                                         -3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64                                                                                                                                                         -3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/                                                                                                                                                         cffi
      copying cffi/commontypes.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      copying cffi/_cffi_include.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3                                                                                                                                                         .7/cffi
      copying cffi/parse_c_type.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      copying cffi/_embedding.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/                                                                                                                                                         cffi
      copying cffi/_cffi_errors.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.                                                                                                                                                         7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7
      creating build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7/c
      cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG                                                                                                                                                          -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/include/ffi                                                                                                                                                          -I/usr/include/libffi -I/usr/local/include -I/usr/local/include/python3.7m -c c                                                                                                                                                         /_cffi_backend.c -o build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7/c/_cffi_backen                                                                                                                                                         d.o
      unable to execute 'cc': No such file or directory
      error: command 'cc' failed with exit status 1
      ----------------------------------------
  ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__                                                                                                                                                         file__='"'"'/tmp/pip-install-g0e1xhci/cffi/setup.py'"'"';f=getattr(tokenize, '"'                                                                                                                                                         "'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"')                                                                                                                                                         ;f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/                                                                                                                                                         pip-record-8tldunwo/install-record.txt --single-version-externally-managed --pre                                                                                                                                                         fix /tmp/pip-build-env-y89sy82c/overlay --compile" failed with error code 1 in /                                                                                                                                                         tmp/pip-install-g0e1xhci/cffi/
  ----------------------------------------
ERROR: Command "/usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/                                                                                                                                                         pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-y89sy82c/ov                                                                                                                                                         erlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https                                                                                                                                                         ://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_p                                                                                                                                                         ython_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None
[admin@polisy /var/polyglot/nodeservers/LutronCaseta]$ ./install.sh
Collecting polyinterface>=2.0.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a8/33/56195e3c280a21f78de39f81c9aa4bf63215eeb550a7dc552ee91001d002/polyinterface-2.0.31.tar.gz
Collecting markdown2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/89/d2/6aef45472f7956646fdc4cc5284e6f9d00476497a8d167c30b0f78bb75a5/markdown2-2.3.8-py2.py3-none-any.whl
Collecting cryptography>=2.3 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz
  Installing build dependencies ... -cryptographerror
  ERROR: Complete output from command /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jl_mjnn2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'':
  ERROR: Collecting setuptools>=40.6.0
    Using cached https://files.pythonhosted.org/packages/db/3c/1065553af43e5f388cb5ae96f44867470063a2d04c02551104dcb12794bd/setuptools-41.5.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting cffi!=1.11.3,>=1.8
    Using cached https://files.pythonhosted.org/packages/0d/aa/c5ac2f337d9a10ee95d160d47beb8d9400e1b2a46bb94990a0409fe6d133/cffi-1.13.1.tar.gz
  Collecting pycparser (from cffi!=1.11.3,>=1.8)
    Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
  Installing collected packages: setuptools, wheel, pycparser, cffi
    Running setup.py install for pycparser: started
      Running setup.py install for pycparser: finished with status 'done'
    Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Complete output from command /usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rruibed2/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0_r9glgp/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-jl_mjnn2/overlay --compile:
      ERROR: unable to execute 'cc': No such file or directory
      unable to execute 'cc': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7
      creating build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/commontypes.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/verifier.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/model.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/recompiler.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/__init__.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/api.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/lock.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/error.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/cparser.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/_cffi_include.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/parse_c_type.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/_embedding.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7
      creating build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7/c
      cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7/c/_cffi_backend.o
      unable to execute 'cc': No such file or directory
      error: command 'cc' failed with exit status 1
      ----------------------------------------
  ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rruibed2/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0_r9glgp/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-jl_mjnn2/overlay --compile" failed with error code 1 in /tmp/pip-install-rruibed2/cffi/
  ----------------------------------------
ERROR: Command "/usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jl_mjnn2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None
[admin@polisy /var/polyglot/nodeservers/LutronCaseta]$ cc
-bash: cc: command not found
[admin@polisy /var/polyglot/nodeservers/LutronCaseta]$ cc
-bash: cc: command not found
[admin@polisy /var/polyglot/nodeservers/LutronCaseta]$ clear
[admin@polisy /var/polyglot/nodeservers/LutronCaseta]$ ./install.sh
Collecting polyinterface>=2.0.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a8/33/56195e3c280a21f78de39f81c9aa4bf63215eeb550a7dc552ee91001d002/polyinterface-2.0.31.tar.gz
Collecting markdown2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/89/d2/6aef45472f7956646fdc4cc5284e6f9d00476497a8d167c30b0f78bb75a5/markdown2-2.3.8-py2.py3-none-any.whl
Collecting cryptography>=2.3 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz
  Installing build dependencies ... error
  ERROR: Complete output from command /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-xpt2p7kn/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'':
  ERROR: Collecting setuptools>=40.6.0
    Using cached https://files.pythonhosted.org/packages/db/3c/1065553af43e5f388cb5ae96f44867470063a2d04c02551104dcb12794bd/setuptools-41.5.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting cffi!=1.11.3,>=1.8
    Using cached https://files.pythonhosted.org/packages/0d/aa/c5ac2f337d9a10ee95d160d47beb8d9400e1b2a46bb94990a0409fe6d133/cffi-1.13.1.tar.gz
  Collecting pycparser (from cffi!=1.11.3,>=1.8)
    Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
  Installing collected packages: setuptools, wheel, pycparser, cffi
    Running setup.py install for pycparser: started
      Running setup.py install for pycparser: finished with status 'done'
    Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Complete output from command /usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-534o3_dy/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z8ve0uqv/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-xpt2p7kn/overlay --compile:
      ERROR: unable to execute 'cc': No such file or directory
      unable to execute 'cc': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7
      creating build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/api.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/model.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/cparser.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/commontypes.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/verifier.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/lock.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/error.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/recompiler.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/__init__.py -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/_cffi_include.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/parse_c_type.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/_embedding.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.freebsd-12.0-RELEASE-p10-amd64-3.7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7
      creating build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7/c
      cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.freebsd-12.0-RELEASE-p10-amd64-3.7/c/_cffi_backend.o
      unable to execute 'cc': No such file or directory
      error: command 'cc' failed with exit status 1
      ----------------------------------------
  ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-534o3_dy/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z8ve0uqv/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-xpt2p7kn/overlay --compile" failed with error code 1 in /tmp/pip-install-534o3_dy/cffi/
  ----------------------------------------
ERROR: Command "/usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-xpt2p7kn/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None
```

**Comment by avandeputte** [comment]
manually installing the pre-compile library on the polisy fixes the issue.  This seems like an issue with polisy / polyglot on polisy and not with the module itself, so I am gonna close this issue.

`sudo pkg install py37-cryptography-2.6.1`
